using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDanhMuc
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            tabs = new TabControl();
            tab0 = new TabPage();
            dgvPT = new DataGridView();
            label1 = new Label();
            txtPTMa = new TextBox();
            label2 = new Label();
            txtPTTen = new TextBox();
            label3 = new Label();
            txtPTGhiChu = new TextBox();
            btnThemPT = new Button();
            tab1 = new TabPage();
            dgvDB = new DataGridView();
            label4 = new Label();
            txtDBMa = new TextBox();
            label5 = new Label();
            txtDBTen = new TextBox();
            label6 = new Label();
            txtDBDiaChi = new TextBox();
            label7 = new Label();
            txtDBDT = new TextBox();
            btnThemDB = new Button();
            tab2 = new TabPage();
            dgvHDV = new DataGridView();
            label8 = new Label();
            txtHDVMa = new TextBox();
            label9 = new Label();
            txtHDVTen = new TextBox();
            label10 = new Label();
            txtHDVDT = new TextBox();
            label11 = new Label();
            numLuong = new NumericUpDown();
            btnThemHDV = new Button();
            tab3 = new TabPage();
            dgvDTQ = new DataGridView();
            label12 = new Label();
            txtDTQMa = new TextBox();
            label13 = new Label();
            txtDTQTen = new TextBox();
            label14 = new Label();
            txtDTQDiaDiem = new TextBox();
            label15 = new Label();
            txtDTQNoiDung = new TextBox();
            label16 = new Label();
            txtDTQYNghia = new TextBox();
            btnThemDTQ = new Button();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            tabs.Name = "tabs";
            tabs.Location = new Point(20, 20);
            tabs.Size = new Size(1160, 665);
            tabs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(tabs);
            tab0.Name = "tab0";
            tab0.Location = new Point(0, 0);
            tab0.Size = new Size(1150, 635);
            tab0.Text = "Phương tiện";
            tabs.Controls.Add(tab0);
            tab0.UseVisualStyleBackColor = true;
            dgvPT.Name = "dgvPT";
            dgvPT.Location = new Point(15, 15);
            dgvPT.Size = new Size(1115, 385);
            dgvPT.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab0.Controls.Add(dgvPT);
            dgvPT.BackgroundColor = Color.White;
            dgvPT.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvPT.ReadOnly = true;
            dgvPT.AllowUserToAddRows = false;
            dgvPT.AllowUserToDeleteRows = false;
            dgvPT.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvPT.MultiSelect = false;
            dgvPT.RowTemplate.Height = 29;
            dgvPT.ColumnHeadersHeight = 30;
            label1.Name = "label1";
            label1.Location = new Point(20, 420);
            label1.Size = new Size(125, 27);
            label1.Text = "Mã PT:";
            label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtPTMa.Name = "txtPTMa";
            txtPTMa.Location = new Point(145, 420);
            txtPTMa.Size = new Size(210, 30);
            txtPTMa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtPTMa);
            label2.Name = "label2";
            label2.Location = new Point(380, 420);
            label2.Size = new Size(125, 27);
            label2.Text = "Tên PT:";
            label2.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            txtPTTen.Name = "txtPTTen";
            txtPTTen.Location = new Point(505, 420);
            txtPTTen.Size = new Size(210, 30);
            txtPTTen.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtPTTen);
            label3.Name = "label3";
            label3.Location = new Point(740, 420);
            label3.Size = new Size(125, 27);
            label3.Text = "Ghi chú:";
            label3.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            txtPTGhiChu.Name = "txtPTGhiChu";
            txtPTGhiChu.Location = new Point(865, 420);
            txtPTGhiChu.Size = new Size(210, 30);
            txtPTGhiChu.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtPTGhiChu);
            btnThemPT.Name = "btnThemPT";
            btnThemPT.Location = new Point(920, 468);
            btnThemPT.Size = new Size(180, 40);
            btnThemPT.Text = "Thêm phương tiện";
            btnThemPT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(btnThemPT);
            btnThemPT.UseVisualStyleBackColor = true;
            btnThemPT.Click += btnThemPT_Click;
            tab1.Name = "tab1";
            tab1.Location = new Point(0, 0);
            tab1.Size = new Size(1150, 635);
            tab1.Text = "Điểm bán vé";
            tabs.Controls.Add(tab1);
            tab1.UseVisualStyleBackColor = true;
            dgvDB.Name = "dgvDB";
            dgvDB.Location = new Point(15, 15);
            dgvDB.Size = new Size(1115, 385);
            dgvDB.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab1.Controls.Add(dgvDB);
            dgvDB.BackgroundColor = Color.White;
            dgvDB.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvDB.ReadOnly = true;
            dgvDB.AllowUserToAddRows = false;
            dgvDB.AllowUserToDeleteRows = false;
            dgvDB.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvDB.MultiSelect = false;
            dgvDB.RowTemplate.Height = 29;
            dgvDB.ColumnHeadersHeight = 30;
            label4.Name = "label4";
            label4.Location = new Point(20, 420);
            label4.Size = new Size(125, 27);
            label4.Text = "Mã điểm bán:";
            label4.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            txtDBMa.Name = "txtDBMa";
            txtDBMa.Location = new Point(145, 420);
            txtDBMa.Size = new Size(210, 30);
            txtDBMa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtDBMa);
            label5.Name = "label5";
            label5.Location = new Point(380, 420);
            label5.Size = new Size(125, 27);
            label5.Text = "Tên điểm bán:";
            label5.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            txtDBTen.Name = "txtDBTen";
            txtDBTen.Location = new Point(505, 420);
            txtDBTen.Size = new Size(210, 30);
            txtDBTen.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtDBTen);
            label6.Name = "label6";
            label6.Location = new Point(740, 420);
            label6.Size = new Size(125, 27);
            label6.Text = "Địa chỉ:";
            label6.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label6);
            label6.TextAlign = ContentAlignment.MiddleLeft;
            txtDBDiaChi.Name = "txtDBDiaChi";
            txtDBDiaChi.Location = new Point(865, 420);
            txtDBDiaChi.Size = new Size(210, 30);
            txtDBDiaChi.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtDBDiaChi);
            label7.Name = "label7";
            label7.Location = new Point(20, 468);
            label7.Size = new Size(125, 27);
            label7.Text = "Điện thoại:";
            label7.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label7);
            label7.TextAlign = ContentAlignment.MiddleLeft;
            txtDBDT.Name = "txtDBDT";
            txtDBDT.Location = new Point(145, 468);
            txtDBDT.Size = new Size(210, 30);
            txtDBDT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtDBDT);
            btnThemDB.Name = "btnThemDB";
            btnThemDB.Location = new Point(920, 516);
            btnThemDB.Size = new Size(180, 40);
            btnThemDB.Text = "Thêm điểm bán";
            btnThemDB.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(btnThemDB);
            btnThemDB.UseVisualStyleBackColor = true;
            btnThemDB.Click += btnThemDB_Click;
            tab2.Name = "tab2";
            tab2.Location = new Point(0, 0);
            tab2.Size = new Size(1150, 635);
            tab2.Text = "Hướng dẫn viên";
            tabs.Controls.Add(tab2);
            tab2.UseVisualStyleBackColor = true;
            dgvHDV.Name = "dgvHDV";
            dgvHDV.Location = new Point(15, 15);
            dgvHDV.Size = new Size(1115, 385);
            dgvHDV.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab2.Controls.Add(dgvHDV);
            dgvHDV.BackgroundColor = Color.White;
            dgvHDV.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvHDV.ReadOnly = true;
            dgvHDV.AllowUserToAddRows = false;
            dgvHDV.AllowUserToDeleteRows = false;
            dgvHDV.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvHDV.MultiSelect = false;
            dgvHDV.RowTemplate.Height = 29;
            dgvHDV.ColumnHeadersHeight = 30;
            label8.Name = "label8";
            label8.Location = new Point(20, 420);
            label8.Size = new Size(125, 27);
            label8.Text = "Mã HDV:";
            label8.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label8);
            label8.TextAlign = ContentAlignment.MiddleLeft;
            txtHDVMa.Name = "txtHDVMa";
            txtHDVMa.Location = new Point(145, 420);
            txtHDVMa.Size = new Size(210, 30);
            txtHDVMa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(txtHDVMa);
            label9.Name = "label9";
            label9.Location = new Point(380, 420);
            label9.Size = new Size(125, 27);
            label9.Text = "Họ tên:";
            label9.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label9);
            label9.TextAlign = ContentAlignment.MiddleLeft;
            txtHDVTen.Name = "txtHDVTen";
            txtHDVTen.Location = new Point(505, 420);
            txtHDVTen.Size = new Size(210, 30);
            txtHDVTen.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(txtHDVTen);
            label10.Name = "label10";
            label10.Location = new Point(740, 420);
            label10.Size = new Size(125, 27);
            label10.Text = "Điện thoại:";
            label10.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label10);
            label10.TextAlign = ContentAlignment.MiddleLeft;
            txtHDVDT.Name = "txtHDVDT";
            txtHDVDT.Location = new Point(865, 420);
            txtHDVDT.Size = new Size(210, 30);
            txtHDVDT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(txtHDVDT);
            label11.Name = "label11";
            label11.Location = new Point(20, 468);
            label11.Size = new Size(125, 27);
            label11.Text = "Lương cơ bản:";
            label11.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label11);
            label11.TextAlign = ContentAlignment.MiddleLeft;
            numLuong.Name = "numLuong";
            numLuong.Location = new Point(145, 468);
            numLuong.Size = new Size(210, 30);
            numLuong.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(numLuong);
            btnThemHDV.Name = "btnThemHDV";
            btnThemHDV.Location = new Point(920, 516);
            btnThemHDV.Size = new Size(180, 40);
            btnThemHDV.Text = "Thêm HDV";
            btnThemHDV.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(btnThemHDV);
            btnThemHDV.UseVisualStyleBackColor = true;
            btnThemHDV.Click += btnThemHDV_Click;
            tab3.Name = "tab3";
            tab3.Location = new Point(0, 0);
            tab3.Size = new Size(1150, 635);
            tab3.Text = "Điểm tham quan";
            tabs.Controls.Add(tab3);
            tab3.UseVisualStyleBackColor = true;
            dgvDTQ.Name = "dgvDTQ";
            dgvDTQ.Location = new Point(15, 15);
            dgvDTQ.Size = new Size(1115, 385);
            dgvDTQ.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab3.Controls.Add(dgvDTQ);
            dgvDTQ.BackgroundColor = Color.White;
            dgvDTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvDTQ.ReadOnly = true;
            dgvDTQ.AllowUserToAddRows = false;
            dgvDTQ.AllowUserToDeleteRows = false;
            dgvDTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvDTQ.MultiSelect = false;
            dgvDTQ.RowTemplate.Height = 29;
            dgvDTQ.ColumnHeadersHeight = 30;
            label12.Name = "label12";
            label12.Location = new Point(20, 420);
            label12.Size = new Size(125, 27);
            label12.Text = "Mã điểm TQ:";
            label12.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label12);
            label12.TextAlign = ContentAlignment.MiddleLeft;
            txtDTQMa.Name = "txtDTQMa";
            txtDTQMa.Location = new Point(145, 420);
            txtDTQMa.Size = new Size(210, 30);
            txtDTQMa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(txtDTQMa);
            label13.Name = "label13";
            label13.Location = new Point(380, 420);
            label13.Size = new Size(125, 27);
            label13.Text = "Tên điểm TQ:";
            label13.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label13);
            label13.TextAlign = ContentAlignment.MiddleLeft;
            txtDTQTen.Name = "txtDTQTen";
            txtDTQTen.Location = new Point(505, 420);
            txtDTQTen.Size = new Size(210, 30);
            txtDTQTen.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(txtDTQTen);
            label14.Name = "label14";
            label14.Location = new Point(740, 420);
            label14.Size = new Size(125, 27);
            label14.Text = "Địa điểm:";
            label14.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label14);
            label14.TextAlign = ContentAlignment.MiddleLeft;
            txtDTQDiaDiem.Name = "txtDTQDiaDiem";
            txtDTQDiaDiem.Location = new Point(865, 420);
            txtDTQDiaDiem.Size = new Size(210, 30);
            txtDTQDiaDiem.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(txtDTQDiaDiem);
            label15.Name = "label15";
            label15.Location = new Point(20, 468);
            label15.Size = new Size(125, 27);
            label15.Text = "Nội dung:";
            label15.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label15);
            label15.TextAlign = ContentAlignment.MiddleLeft;
            txtDTQNoiDung.Name = "txtDTQNoiDung";
            txtDTQNoiDung.Location = new Point(145, 468);
            txtDTQNoiDung.Size = new Size(210, 30);
            txtDTQNoiDung.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(txtDTQNoiDung);
            label16.Name = "label16";
            label16.Location = new Point(380, 468);
            label16.Size = new Size(125, 27);
            label16.Text = "Ý nghĩa:";
            label16.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label16);
            label16.TextAlign = ContentAlignment.MiddleLeft;
            txtDTQYNghia.Name = "txtDTQYNghia";
            txtDTQYNghia.Location = new Point(505, 468);
            txtDTQYNghia.Size = new Size(210, 30);
            txtDTQYNghia.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(txtDTQYNghia);
            btnThemDTQ.Name = "btnThemDTQ";
            btnThemDTQ.Location = new Point(920, 516);
            btnThemDTQ.Size = new Size(180, 40);
            btnThemDTQ.Text = "Thêm điểm tham quan";
            btnThemDTQ.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(btnThemDTQ);
            btnThemDTQ.UseVisualStyleBackColor = true;
            btnThemDTQ.Click += btnThemDTQ_Click;
            numLuong.Minimum = 0m;
            numLuong.Maximum = 1000000000000m;
            numLuong.Value = 0m;
            numLuong.ThousandsSeparator = true;
            Load += FrmDanhMuc_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmDanhMuc";
            Text = "Danh mục";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private TabControl tabs;
        private TabPage tab0;
        private DataGridView dgvPT;
        private Label label1;
        private TextBox txtPTMa;
        private Label label2;
        private TextBox txtPTTen;
        private Label label3;
        private TextBox txtPTGhiChu;
        private Button btnThemPT;
        private TabPage tab1;
        private DataGridView dgvDB;
        private Label label4;
        private TextBox txtDBMa;
        private Label label5;
        private TextBox txtDBTen;
        private Label label6;
        private TextBox txtDBDiaChi;
        private Label label7;
        private TextBox txtDBDT;
        private Button btnThemDB;
        private TabPage tab2;
        private DataGridView dgvHDV;
        private Label label8;
        private TextBox txtHDVMa;
        private Label label9;
        private TextBox txtHDVTen;
        private Label label10;
        private TextBox txtHDVDT;
        private Label label11;
        private NumericUpDown numLuong;
        private Button btnThemHDV;
        private TabPage tab3;
        private DataGridView dgvDTQ;
        private Label label12;
        private TextBox txtDTQMa;
        private Label label13;
        private TextBox txtDTQTen;
        private Label label14;
        private TextBox txtDTQDiaDiem;
        private Label label15;
        private TextBox txtDTQNoiDung;
        private Label label16;
        private TextBox txtDTQYNghia;
        private Button btnThemDTQ;
    }
}
