using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmKetThucKhaoSat
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            tabs = new TabControl();
            tab0 = new TabPage();
            dgvDoan = new DataGridView();
            label1 = new Label();
            txtSoTT = new TextBox();
            label2 = new Label();
            txtSoDK = new TextBox();
            label3 = new Label();
            dtTT = new DateTimePicker();
            label4 = new Label();
            numTien = new NumericUpDown();
            label5 = new Label();
            txtGhiChu = new TextBox();
            btnThanhToan = new Button();
            tab1 = new TabPage();
            label6 = new Label();
            cboLoaiKS = new ComboBox();
            label7 = new Label();
            cboDangKy = new ComboBox();
            label8 = new Label();
            txtMaKS = new TextBox();
            label9 = new Label();
            dtGui = new DateTimePicker();
            btnGui = new Button();
            dgvKS = new DataGridView();
            label10 = new Label();
            txtKSChon = new TextBox();
            label11 = new Label();
            dtPH = new DateTimePicker();
            label12 = new Label();
            numDiem = new NumericUpDown();
            label13 = new Label();
            txtGopY = new TextBox();
            btnGhiPH = new Button();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            tabs.Name = "tabs";
            tabs.Location = new Point(20, 20);
            tabs.Size = new Size(1160, 665);
            tabs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(tabs);
            tab0.Name = "tab0";
            tab0.Location = new Point(0, 0);
            tab0.Size = new Size(1150, 635);
            tab0.Text = "Thanh toán đoàn";
            tabs.Controls.Add(tab0);
            tab0.UseVisualStyleBackColor = true;
            dgvDoan.Name = "dgvDoan";
            dgvDoan.Location = new Point(15, 15);
            dgvDoan.Size = new Size(1115, 385);
            dgvDoan.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab0.Controls.Add(dgvDoan);
            dgvDoan.BackgroundColor = Color.White;
            dgvDoan.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvDoan.ReadOnly = true;
            dgvDoan.AllowUserToAddRows = false;
            dgvDoan.AllowUserToDeleteRows = false;
            dgvDoan.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvDoan.MultiSelect = false;
            dgvDoan.RowTemplate.Height = 29;
            dgvDoan.ColumnHeadersHeight = 30;
            label1.Name = "label1";
            label1.Location = new Point(20, 420);
            label1.Size = new Size(125, 27);
            label1.Text = "Số thanh toán:";
            label1.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtSoTT.Name = "txtSoTT";
            txtSoTT.Location = new Point(145, 420);
            txtSoTT.Size = new Size(210, 30);
            txtSoTT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtSoTT);
            label2.Name = "label2";
            label2.Location = new Point(380, 420);
            label2.Size = new Size(125, 27);
            label2.Text = "Phiếu đoàn:";
            label2.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            txtSoDK.Name = "txtSoDK";
            txtSoDK.Location = new Point(505, 420);
            txtSoDK.Size = new Size(210, 30);
            txtSoDK.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtSoDK);
            label3.Name = "label3";
            label3.Location = new Point(740, 420);
            label3.Size = new Size(125, 27);
            label3.Text = "Ngày thanh toán:";
            label3.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            dtTT.Name = "dtTT";
            dtTT.Location = new Point(865, 420);
            dtTT.Size = new Size(210, 30);
            dtTT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(dtTT);
            label4.Name = "label4";
            label4.Location = new Point(20, 468);
            label4.Size = new Size(125, 27);
            label4.Text = "Số tiền:";
            label4.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            numTien.Name = "numTien";
            numTien.Location = new Point(145, 468);
            numTien.Size = new Size(210, 30);
            numTien.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(numTien);
            label5.Name = "label5";
            label5.Location = new Point(380, 468);
            label5.Size = new Size(125, 27);
            label5.Text = "Ghi chú:";
            label5.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            txtGhiChu.Name = "txtGhiChu";
            txtGhiChu.Location = new Point(505, 468);
            txtGhiChu.Size = new Size(210, 30);
            txtGhiChu.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtGhiChu);
            btnThanhToan.Name = "btnThanhToan";
            btnThanhToan.Location = new Point(920, 516);
            btnThanhToan.Size = new Size(180, 40);
            btnThanhToan.Text = "Ghi nhận thanh toán";
            btnThanhToan.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(btnThanhToan);
            btnThanhToan.UseVisualStyleBackColor = true;
            btnThanhToan.Click += btnThanhToan_Click;
            tab1.Name = "tab1";
            tab1.Location = new Point(0, 0);
            tab1.Size = new Size(1150, 635);
            tab1.Text = "Khảo sát khách hàng";
            tabs.Controls.Add(tab1);
            tab1.UseVisualStyleBackColor = true;
            label6.Name = "label6";
            label6.Location = new Point(20, 20);
            label6.Size = new Size(130, 27);
            label6.Text = "Loại khách:";
            tab1.Controls.Add(label6);
            label6.TextAlign = ContentAlignment.MiddleLeft;
            cboLoaiKS.Name = "cboLoaiKS";
            cboLoaiKS.Location = new Point(150, 20);
            cboLoaiKS.Size = new Size(200, 30);
            tab1.Controls.Add(cboLoaiKS);
            label7.Name = "label7";
            label7.Location = new Point(380, 20);
            label7.Size = new Size(130, 27);
            label7.Text = "Đăng ký kết thúc:";
            tab1.Controls.Add(label7);
            label7.TextAlign = ContentAlignment.MiddleLeft;
            cboDangKy.Name = "cboDangKy";
            cboDangKy.Location = new Point(510, 20);
            cboDangKy.Size = new Size(200, 30);
            tab1.Controls.Add(cboDangKy);
            label8.Name = "label8";
            label8.Location = new Point(740, 20);
            label8.Size = new Size(130, 27);
            label8.Text = "Mã khảo sát:";
            tab1.Controls.Add(label8);
            label8.TextAlign = ContentAlignment.MiddleLeft;
            txtMaKS.Name = "txtMaKS";
            txtMaKS.Location = new Point(870, 20);
            txtMaKS.Size = new Size(200, 30);
            tab1.Controls.Add(txtMaKS);
            label9.Name = "label9";
            label9.Location = new Point(20, 68);
            label9.Size = new Size(130, 27);
            label9.Text = "Ngày gửi:";
            tab1.Controls.Add(label9);
            label9.TextAlign = ContentAlignment.MiddleLeft;
            dtGui.Name = "dtGui";
            dtGui.Location = new Point(150, 68);
            dtGui.Size = new Size(200, 30);
            tab1.Controls.Add(dtGui);
            btnGui.Name = "btnGui";
            btnGui.Location = new Point(920, 65);
            btnGui.Size = new Size(180, 40);
            btnGui.Text = "Gửi phiếu khảo sát";
            tab1.Controls.Add(btnGui);
            btnGui.UseVisualStyleBackColor = true;
            btnGui.Click += btnGui_Click;
            dgvKS.Name = "dgvKS";
            dgvKS.Location = new Point(15, 125);
            dgvKS.Size = new Size(1115, 285);
            dgvKS.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab1.Controls.Add(dgvKS);
            dgvKS.BackgroundColor = Color.White;
            dgvKS.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvKS.ReadOnly = true;
            dgvKS.AllowUserToAddRows = false;
            dgvKS.AllowUserToDeleteRows = false;
            dgvKS.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvKS.MultiSelect = false;
            dgvKS.RowTemplate.Height = 29;
            dgvKS.ColumnHeadersHeight = 30;
            label10.Name = "label10";
            label10.Location = new Point(20, 435);
            label10.Size = new Size(130, 27);
            label10.Text = "Phiếu chọn:";
            label10.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label10);
            label10.TextAlign = ContentAlignment.MiddleLeft;
            txtKSChon.Name = "txtKSChon";
            txtKSChon.Location = new Point(150, 435);
            txtKSChon.Size = new Size(210, 30);
            txtKSChon.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtKSChon);
            label11.Name = "label11";
            label11.Location = new Point(380, 435);
            label11.Size = new Size(130, 27);
            label11.Text = "Ngày phản hồi:";
            label11.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label11);
            label11.TextAlign = ContentAlignment.MiddleLeft;
            dtPH.Name = "dtPH";
            dtPH.Location = new Point(510, 435);
            dtPH.Size = new Size(210, 30);
            dtPH.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(dtPH);
            label12.Name = "label12";
            label12.Location = new Point(740, 435);
            label12.Size = new Size(130, 27);
            label12.Text = "Điểm (1–5):";
            label12.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label12);
            label12.TextAlign = ContentAlignment.MiddleLeft;
            numDiem.Name = "numDiem";
            numDiem.Location = new Point(870, 435);
            numDiem.Size = new Size(210, 30);
            numDiem.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(numDiem);
            label13.Name = "label13";
            label13.Location = new Point(20, 485);
            label13.Size = new Size(130, 27);
            label13.Text = "Góp ý:";
            label13.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label13);
            label13.TextAlign = ContentAlignment.MiddleLeft;
            txtGopY.Name = "txtGopY";
            txtGopY.Location = new Point(150, 485);
            txtGopY.Size = new Size(210, 30);
            txtGopY.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtGopY);
            btnGhiPH.Name = "btnGhiPH";
            btnGhiPH.Location = new Point(920, 490);
            btnGhiPH.Size = new Size(180, 40);
            btnGhiPH.Text = "Ghi nhận góp ý";
            btnGhiPH.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(btnGhiPH);
            btnGhiPH.UseVisualStyleBackColor = true;
            btnGhiPH.Click += btnGhiPH_Click;
            dtTT.Format = DateTimePickerFormat.Custom;
            dtTT.CustomFormat = "dd/MM/yyyy";
            numTien.Minimum = 0m;
            numTien.Maximum = 1000000000000m;
            numTien.Value = 0m;
            numTien.ThousandsSeparator = true;
            cboLoaiKS.DropDownStyle = ComboBoxStyle.DropDownList;
            cboDangKy.DropDownStyle = ComboBoxStyle.DropDownList;
            dtGui.Format = DateTimePickerFormat.Custom;
            dtGui.CustomFormat = "dd/MM/yyyy";
            dtPH.Format = DateTimePickerFormat.Custom;
            dtPH.CustomFormat = "dd/MM/yyyy";
            numDiem.Minimum = 1m;
            numDiem.Maximum = 5m;
            numDiem.Value = 5m;
            numDiem.ThousandsSeparator = true;
            txtSoDK.ReadOnly = true;
            txtKSChon.ReadOnly = true;
            dgvDoan.SelectionChanged += dgvDoan_SelectionChanged;
            cboLoaiKS.SelectedIndexChanged += cboLoaiKS_SelectedIndexChanged;
            dgvKS.SelectionChanged += dgvKS_SelectionChanged;
            Load += FrmKetThucKhaoSat_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmKetThucKhaoSat";
            Text = "Kết thúc tour và khảo sát";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private TabControl tabs;
        private TabPage tab0;
        private DataGridView dgvDoan;
        private Label label1;
        private TextBox txtSoTT;
        private Label label2;
        private TextBox txtSoDK;
        private Label label3;
        private DateTimePicker dtTT;
        private Label label4;
        private NumericUpDown numTien;
        private Label label5;
        private TextBox txtGhiChu;
        private Button btnThanhToan;
        private TabPage tab1;
        private Label label6;
        private ComboBox cboLoaiKS;
        private Label label7;
        private ComboBox cboDangKy;
        private Label label8;
        private TextBox txtMaKS;
        private Label label9;
        private DateTimePicker dtGui;
        private Button btnGui;
        private DataGridView dgvKS;
        private Label label10;
        private TextBox txtKSChon;
        private Label label11;
        private DateTimePicker dtPH;
        private Label label12;
        private NumericUpDown numDiem;
        private Label label13;
        private TextBox txtGopY;
        private Button btnGhiPH;
    }
}
