using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmLuongThongKe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            tabs = new TabControl();
            tab0 = new TabPage();
            label1 = new Label();
            numThang = new NumericUpDown();
            label2 = new Label();
            numNam = new NumericUpDown();
            btnLuong = new Button();
            dgvLuong = new DataGridView();
            tab1 = new TabPage();
            label3 = new Label();
            dtTu = new DateTimePicker();
            label4 = new Label();
            dtDen = new DateTimePicker();
            btnTongHop = new Button();
            dgvTongHop = new DataGridView();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            tabs.Name = "tabs";
            tabs.Location = new Point(20, 20);
            tabs.Size = new Size(1160, 665);
            tabs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(tabs);
            tab0.Name = "tab0";
            tab0.Location = new Point(0, 0);
            tab0.Size = new Size(1150, 635);
            tab0.Text = "Lương hướng dẫn viên";
            tabs.Controls.Add(tab0);
            tab0.UseVisualStyleBackColor = true;
            label1.Name = "label1";
            label1.Location = new Point(20, 20);
            label1.Size = new Size(75, 27);
            label1.Text = "Tháng:";
            tab0.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            numThang.Name = "numThang";
            numThang.Location = new Point(95, 20);
            numThang.Size = new Size(110, 30);
            tab0.Controls.Add(numThang);
            label2.Name = "label2";
            label2.Location = new Point(255, 20);
            label2.Size = new Size(75, 27);
            label2.Text = "Năm:";
            tab0.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            numNam.Name = "numNam";
            numNam.Location = new Point(330, 20);
            numNam.Size = new Size(110, 30);
            tab0.Controls.Add(numNam);
            btnLuong.Name = "btnLuong";
            btnLuong.Location = new Point(510, 18);
            btnLuong.Size = new Size(155, 40);
            btnLuong.Text = "Tính lương";
            tab0.Controls.Add(btnLuong);
            btnLuong.UseVisualStyleBackColor = true;
            btnLuong.Click += btnLuong_Click;
            dgvLuong.Name = "dgvLuong";
            dgvLuong.Location = new Point(15, 80);
            dgvLuong.Size = new Size(1115, 505);
            dgvLuong.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab0.Controls.Add(dgvLuong);
            dgvLuong.BackgroundColor = Color.White;
            dgvLuong.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvLuong.ReadOnly = true;
            dgvLuong.AllowUserToAddRows = false;
            dgvLuong.AllowUserToDeleteRows = false;
            dgvLuong.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvLuong.MultiSelect = false;
            dgvLuong.RowTemplate.Height = 29;
            dgvLuong.ColumnHeadersHeight = 30;
            tab1.Name = "tab1";
            tab1.Location = new Point(0, 0);
            tab1.Size = new Size(1150, 635);
            tab1.Text = "Thống kê tổng hợp";
            tabs.Controls.Add(tab1);
            tab1.UseVisualStyleBackColor = true;
            label3.Name = "label3";
            label3.Location = new Point(20, 20);
            label3.Size = new Size(75, 27);
            label3.Text = "Từ ngày:";
            tab1.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            dtTu.Name = "dtTu";
            dtTu.Location = new Point(95, 20);
            dtTu.Size = new Size(110, 30);
            tab1.Controls.Add(dtTu);
            label4.Name = "label4";
            label4.Location = new Point(255, 20);
            label4.Size = new Size(75, 27);
            label4.Text = "Đến ngày:";
            tab1.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            dtDen.Name = "dtDen";
            dtDen.Location = new Point(330, 20);
            dtDen.Size = new Size(110, 30);
            tab1.Controls.Add(dtDen);
            btnTongHop.Name = "btnTongHop";
            btnTongHop.Location = new Point(510, 18);
            btnTongHop.Size = new Size(155, 40);
            btnTongHop.Text = "Thống kê";
            tab1.Controls.Add(btnTongHop);
            btnTongHop.UseVisualStyleBackColor = true;
            btnTongHop.Click += btnTongHop_Click;
            dgvTongHop.Name = "dgvTongHop";
            dgvTongHop.Location = new Point(15, 80);
            dgvTongHop.Size = new Size(1115, 505);
            dgvTongHop.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab1.Controls.Add(dgvTongHop);
            dgvTongHop.BackgroundColor = Color.White;
            dgvTongHop.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvTongHop.ReadOnly = true;
            dgvTongHop.AllowUserToAddRows = false;
            dgvTongHop.AllowUserToDeleteRows = false;
            dgvTongHop.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvTongHop.MultiSelect = false;
            dgvTongHop.RowTemplate.Height = 29;
            dgvTongHop.ColumnHeadersHeight = 30;
            numThang.Minimum = 1m;
            numThang.Maximum = 12m;
            numThang.Value = 1m;
            numThang.ThousandsSeparator = false;
            numNam.Minimum = 1900m;
            numNam.Maximum = 2200m;
            numNam.Value = 2026m;
            numNam.ThousandsSeparator = false;
            dtTu.Format = DateTimePickerFormat.Custom;
            dtTu.CustomFormat = "dd/MM/yyyy";
            dtDen.Format = DateTimePickerFormat.Custom;
            dtDen.CustomFormat = "dd/MM/yyyy";
            Load += FrmLuongThongKe_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmLuongThongKe";
            Text = "Lương và thống kê";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private TabControl tabs;
        private TabPage tab0;
        private Label label1;
        private NumericUpDown numThang;
        private Label label2;
        private NumericUpDown numNam;
        private Button btnLuong;
        private DataGridView dgvLuong;
        private TabPage tab1;
        private Label label3;
        private DateTimePicker dtTu;
        private Label label4;
        private DateTimePicker dtDen;
        private Button btnTongHop;
        private DataGridView dgvTongHop;
    }
}
