using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmChuyenLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            label1 = new Label();
            txtMa = new TextBox();
            label2 = new Label();
            cboTour = new ComboBox();
            label3 = new Label();
            dtDi = new DateTimePicker();
            label4 = new Label();
            txtDon = new TextBox();
            label5 = new Label();
            lblNgayVe = new Label();
            btnThem = new Button();
            btnDongDK = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            label1.Name = "label1";
            label1.Location = new Point(25, 20);
            label1.Size = new Size(110, 27);
            label1.Text = "Mã chuyến:";
            this.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtMa.Name = "txtMa";
            txtMa.Location = new Point(135, 20);
            txtMa.Size = new Size(190, 30);
            this.Controls.Add(txtMa);
            label2.Name = "label2";
            label2.Location = new Point(350, 20);
            label2.Size = new Size(90, 27);
            label2.Text = "Tour:";
            this.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            cboTour.Name = "cboTour";
            cboTour.Location = new Point(440, 20);
            cboTour.Size = new Size(420, 30);
            this.Controls.Add(cboTour);
            label3.Name = "label3";
            label3.Location = new Point(25, 70);
            label3.Size = new Size(110, 27);
            label3.Text = "Ngày đi:";
            this.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            dtDi.Name = "dtDi";
            dtDi.Location = new Point(135, 70);
            dtDi.Size = new Size(190, 30);
            this.Controls.Add(dtDi);
            label4.Name = "label4";
            label4.Location = new Point(25, 120);
            label4.Size = new Size(110, 27);
            label4.Text = "Địa điểm đón:";
            this.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            txtDon.Name = "txtDon";
            txtDon.Location = new Point(135, 120);
            txtDon.Size = new Size(690, 30);
            this.Controls.Add(txtDon);
            label5.Name = "label5";
            label5.Location = new Point(350, 70);
            label5.Size = new Size(90, 27);
            label5.Text = "Ngày về:";
            this.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            lblNgayVe.Name = "lblNgayVe";
            lblNgayVe.Location = new Point(440, 70);
            lblNgayVe.Size = new Size(180, 30);
            this.Controls.Add(lblNgayVe);
            btnThem.Name = "btnThem";
            btnThem.Location = new Point(980, 175);
            btnThem.Size = new Size(195, 40);
            btnThem.Text = "Tạo chuyến";
            this.Controls.Add(btnThem);
            btnThem.UseVisualStyleBackColor = true;
            btnThem.Click += btnThem_Click;
            btnDongDK.Name = "btnDongDK";
            btnDongDK.Location = new Point(770, 175);
            btnDongDK.Size = new Size(195, 40);
            btnDongDK.Text = "Đóng đăng ký";
            this.Controls.Add(btnDongDK);
            btnDongDK.UseVisualStyleBackColor = true;
            btnDongDK.Click += btnDongDK_Click;
            dgv.Name = "dgv";
            dgv.Location = new Point(20, 235);
            dgv.Size = new Size(1160, 450);
            dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(dgv);
            dgv.BackgroundColor = Color.White;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.MultiSelect = false;
            dgv.RowTemplate.Height = 29;
            dgv.ColumnHeadersHeight = 30;
            cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            dtDi.Format = DateTimePickerFormat.Custom;
            dtDi.CustomFormat = "dd/MM/yyyy";
            lblNgayVe.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblNgayVe.Text = "-";
            cboTour.SelectedIndexChanged += TinhNgayVe;
            dtDi.ValueChanged += TinhNgayVe;
            Load += FrmChuyenLe_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmChuyenLe";
            Text = "Lịch chuyến khách lẻ";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private Label label1;
        private TextBox txtMa;
        private Label label2;
        private ComboBox cboTour;
        private Label label3;
        private DateTimePicker dtDi;
        private Label label4;
        private TextBox txtDon;
        private Label label5;
        private Label lblNgayVe;
        private Button btnThem;
        private Button btnDongDK;
        private DataGridView dgv;
    }
}
