using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyDoan
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            grpDoan = new GroupBox();
            grpDangKy = new GroupBox();
            label1 = new Label();
            txtMaDoan = new TextBox();
            label2 = new Label();
            txtTenCQ = new TextBox();
            label3 = new Label();
            txtDiaChi = new TextBox();
            label4 = new Label();
            txtDT = new TextBox();
            label5 = new Label();
            txtDaiDien = new TextBox();
            label6 = new Label();
            txtSo = new TextBox();
            label7 = new Label();
            cboTour = new ComboBox();
            label8 = new Label();
            dtDi = new DateTimePicker();
            label9 = new Label();
            numNguoi = new NumericUpDown();
            label10 = new Label();
            txtDon = new TextBox();
            label11 = new Label();
            numCoc = new NumericUpDown();
            chkBH = new CheckBox();
            label12 = new Label();
            lblKetThuc = new Label();
            label13 = new Label();
            lblTong = new Label();
            label14 = new Label();
            dgvThanhVien = new DataGridView();
            btnDangKy = new Button();
            btnHuy = new Button();
            label15 = new Label();
            dgv = new DataGridView();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            grpDoan.Name = "grpDoan";
            grpDoan.Location = new Point(20, 15);
            grpDoan.Size = new Size(560, 260);
            grpDoan.Text = "Thông tin đoàn khách";
            this.Controls.Add(grpDoan);
            grpDangKy.Name = "grpDangKy";
            grpDangKy.Location = new Point(600, 15);
            grpDangKy.Size = new Size(580, 260);
            grpDangKy.Text = "Đăng ký tour";
            this.Controls.Add(grpDangKy);
            label1.Name = "label1";
            label1.Location = new Point(12, 30);
            label1.Size = new Size(140, 27);
            label1.Text = "Mã đoàn:";
            grpDoan.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtMaDoan.Name = "txtMaDoan";
            txtMaDoan.Location = new Point(152, 30);
            txtMaDoan.Size = new Size(380, 30);
            grpDoan.Controls.Add(txtMaDoan);
            label2.Name = "label2";
            label2.Location = new Point(12, 73);
            label2.Size = new Size(140, 27);
            label2.Text = "Cơ quan / gia đình:";
            grpDoan.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            txtTenCQ.Name = "txtTenCQ";
            txtTenCQ.Location = new Point(152, 73);
            txtTenCQ.Size = new Size(380, 30);
            grpDoan.Controls.Add(txtTenCQ);
            label3.Name = "label3";
            label3.Location = new Point(12, 116);
            label3.Size = new Size(140, 27);
            label3.Text = "Địa chỉ:";
            grpDoan.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            txtDiaChi.Name = "txtDiaChi";
            txtDiaChi.Location = new Point(152, 116);
            txtDiaChi.Size = new Size(380, 30);
            grpDoan.Controls.Add(txtDiaChi);
            label4.Name = "label4";
            label4.Location = new Point(12, 159);
            label4.Size = new Size(140, 27);
            label4.Text = "Điện thoại:";
            grpDoan.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            txtDT.Name = "txtDT";
            txtDT.Location = new Point(152, 159);
            txtDT.Size = new Size(380, 30);
            grpDoan.Controls.Add(txtDT);
            label5.Name = "label5";
            label5.Location = new Point(12, 202);
            label5.Size = new Size(140, 27);
            label5.Text = "Người đại diện:";
            grpDoan.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            txtDaiDien.Name = "txtDaiDien";
            txtDaiDien.Location = new Point(152, 202);
            txtDaiDien.Size = new Size(380, 30);
            grpDoan.Controls.Add(txtDaiDien);
            label6.Name = "label6";
            label6.Location = new Point(12, 30);
            label6.Size = new Size(100, 27);
            label6.Text = "Số phiếu:";
            grpDangKy.Controls.Add(label6);
            label6.TextAlign = ContentAlignment.MiddleLeft;
            txtSo.Name = "txtSo";
            txtSo.Location = new Point(112, 30);
            txtSo.Size = new Size(160, 30);
            grpDangKy.Controls.Add(txtSo);
            label7.Name = "label7";
            label7.Location = new Point(292, 30);
            label7.Size = new Size(100, 27);
            label7.Text = "Tour:";
            grpDangKy.Controls.Add(label7);
            label7.TextAlign = ContentAlignment.MiddleLeft;
            cboTour.Name = "cboTour";
            cboTour.Location = new Point(392, 30);
            cboTour.Size = new Size(160, 30);
            grpDangKy.Controls.Add(cboTour);
            label8.Name = "label8";
            label8.Location = new Point(12, 73);
            label8.Size = new Size(100, 27);
            label8.Text = "Ngày đi:";
            grpDangKy.Controls.Add(label8);
            label8.TextAlign = ContentAlignment.MiddleLeft;
            dtDi.Name = "dtDi";
            dtDi.Location = new Point(112, 73);
            dtDi.Size = new Size(160, 30);
            grpDangKy.Controls.Add(dtDi);
            label9.Name = "label9";
            label9.Location = new Point(292, 73);
            label9.Size = new Size(100, 27);
            label9.Text = "Số người:";
            grpDangKy.Controls.Add(label9);
            label9.TextAlign = ContentAlignment.MiddleLeft;
            numNguoi.Name = "numNguoi";
            numNguoi.Location = new Point(392, 73);
            numNguoi.Size = new Size(160, 30);
            grpDangKy.Controls.Add(numNguoi);
            label10.Name = "label10";
            label10.Location = new Point(12, 115);
            label10.Size = new Size(120, 27);
            label10.Text = "Địa điểm đón:";
            grpDangKy.Controls.Add(label10);
            label10.TextAlign = ContentAlignment.MiddleLeft;
            txtDon.Name = "txtDon";
            txtDon.Location = new Point(132, 115);
            txtDon.Size = new Size(430, 30);
            grpDangKy.Controls.Add(txtDon);
            label11.Name = "label11";
            label11.Location = new Point(12, 160);
            label11.Size = new Size(120, 27);
            label11.Text = "Tiền cọc:";
            grpDangKy.Controls.Add(label11);
            label11.TextAlign = ContentAlignment.MiddleLeft;
            numCoc.Name = "numCoc";
            numCoc.Location = new Point(132, 160);
            numCoc.Size = new Size(170, 30);
            grpDangKy.Controls.Add(numCoc);
            chkBH.Name = "chkBH";
            chkBH.Location = new Point(310, 160);
            chkBH.Size = new Size(170, 30);
            chkBH.Text = "Mua bảo hiểm";
            grpDangKy.Controls.Add(chkBH);
            label12.Name = "label12";
            label12.Location = new Point(12, 210);
            label12.Size = new Size(135, 27);
            label12.Text = "Kết thúc DK:";
            grpDangKy.Controls.Add(label12);
            label12.TextAlign = ContentAlignment.MiddleLeft;
            lblKetThuc.Name = "lblKetThuc";
            lblKetThuc.Location = new Point(147, 210);
            lblKetThuc.Size = new Size(140, 30);
            grpDangKy.Controls.Add(lblKetThuc);
            label13.Name = "label13";
            label13.Location = new Point(310, 210);
            label13.Size = new Size(135, 27);
            label13.Text = "Tổng dự kiến:";
            grpDangKy.Controls.Add(label13);
            label13.TextAlign = ContentAlignment.MiddleLeft;
            lblTong.Name = "lblTong";
            lblTong.Location = new Point(445, 210);
            lblTong.Size = new Size(140, 30);
            grpDangKy.Controls.Add(lblTong);
            label14.Name = "label14";
            label14.Location = new Point(20, 288);
            label14.Size = new Size(850, 27);
            label14.Text = "Danh sách người cùng đi (bắt buộc đủ số người khi mua bảo hiểm)";
            this.Controls.Add(label14);
            label14.TextAlign = ContentAlignment.MiddleLeft;
            dgvThanhVien.Name = "dgvThanhVien";
            dgvThanhVien.Location = new Point(20, 320);
            dgvThanhVien.Size = new Size(1160, 145);
            dgvThanhVien.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(dgvThanhVien);
            dgvThanhVien.BackgroundColor = Color.White;
            dgvThanhVien.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvThanhVien.ReadOnly = false;
            dgvThanhVien.AllowUserToAddRows = true;
            dgvThanhVien.AllowUserToDeleteRows = true;
            dgvThanhVien.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvThanhVien.MultiSelect = false;
            dgvThanhVien.RowTemplate.Height = 29;
            dgvThanhVien.ColumnHeadersHeight = 30;
            btnDangKy.Name = "btnDangKy";
            btnDangKy.Location = new Point(790, 480);
            btnDangKy.Size = new Size(185, 40);
            btnDangKy.Text = "Lập phiếu đăng ký";
            btnDangKy.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.Controls.Add(btnDangKy);
            btnDangKy.UseVisualStyleBackColor = true;
            btnDangKy.Click += btnDangKy_Click;
            btnHuy.Name = "btnHuy";
            btnHuy.Location = new Point(990, 480);
            btnHuy.Size = new Size(190, 40);
            btnHuy.Text = "Hủy phiếu (mất cọc)";
            btnHuy.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.Controls.Add(btnHuy);
            btnHuy.UseVisualStyleBackColor = true;
            btnHuy.Click += btnHuy_Click;
            label15.Name = "label15";
            label15.Location = new Point(20, 515);
            label15.Size = new Size(400, 27);
            label15.Text = "Các phiếu đăng ký đoàn";
            label15.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            this.Controls.Add(label15);
            label15.TextAlign = ContentAlignment.MiddleLeft;
            dgv.Name = "dgv";
            dgv.Location = new Point(20, 545);
            dgv.Size = new Size(1160, 145);
            dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(dgv);
            dgv.BackgroundColor = Color.White;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.MultiSelect = false;
            dgv.RowTemplate.Height = 29;
            dgv.ColumnHeadersHeight = 30;
            cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            dtDi.Format = DateTimePickerFormat.Custom;
            dtDi.CustomFormat = "dd/MM/yyyy";
            numNguoi.Minimum = 13m;
            numNguoi.Maximum = 100000m;
            numNguoi.Value = 13m;
            numNguoi.ThousandsSeparator = true;
            numCoc.Minimum = 0m;
            numCoc.Maximum = 1000000000000m;
            numCoc.Value = 0m;
            numCoc.ThousandsSeparator = true;
            lblKetThuc.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblKetThuc.Text = "-";
            lblTong.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblTong.Text = "-";
            lblTong.ForeColor = Color.DarkRed;
            cboTour.SelectedIndexChanged += TinhTong;
            dtDi.ValueChanged += TinhTong;
            numNguoi.ValueChanged += TinhTong;
            chkBH.CheckedChanged += chkBH_CheckedChanged;
            Load += FrmDangKyDoan_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmDangKyDoan";
            Text = "Đăng ký theo đoàn";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private GroupBox grpDoan;
        private GroupBox grpDangKy;
        private Label label1;
        private TextBox txtMaDoan;
        private Label label2;
        private TextBox txtTenCQ;
        private Label label3;
        private TextBox txtDiaChi;
        private Label label4;
        private TextBox txtDT;
        private Label label5;
        private TextBox txtDaiDien;
        private Label label6;
        private TextBox txtSo;
        private Label label7;
        private ComboBox cboTour;
        private Label label8;
        private DateTimePicker dtDi;
        private Label label9;
        private NumericUpDown numNguoi;
        private Label label10;
        private TextBox txtDon;
        private Label label11;
        private NumericUpDown numCoc;
        private CheckBox chkBH;
        private Label label12;
        private Label lblKetThuc;
        private Label label13;
        private Label lblTong;
        private Label label14;
        private DataGridView dgvThanhVien;
        private Button btnDangKy;
        private Button btnHuy;
        private Label label15;
        private DataGridView dgv;
    }
}
