using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmDangKyLe
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            label1 = new Label();
            txtSo = new TextBox();
            label2 = new Label();
            cboChuyen = new ComboBox();
            label3 = new Label();
            cboDiemBan = new ComboBox();
            label4 = new Label();
            txtTen = new TextBox();
            label5 = new Label();
            txtDT = new TextBox();
            label6 = new Label();
            numNguoi = new NumericUpDown();
            label7 = new Label();
            lblThanhTien = new Label();
            btnDangKy = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            label1.Name = "label1";
            label1.Location = new Point(25, 20);
            label1.Size = new Size(110, 27);
            label1.Text = "Số đăng ký:";
            this.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtSo.Name = "txtSo";
            txtSo.Location = new Point(135, 20);
            txtSo.Size = new Size(190, 30);
            this.Controls.Add(txtSo);
            label2.Name = "label2";
            label2.Location = new Point(360, 20);
            label2.Size = new Size(95, 27);
            label2.Text = "Chuyến:";
            this.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            cboChuyen.Name = "cboChuyen";
            cboChuyen.Location = new Point(455, 20);
            cboChuyen.Size = new Size(600, 30);
            this.Controls.Add(cboChuyen);
            label3.Name = "label3";
            label3.Location = new Point(25, 70);
            label3.Size = new Size(110, 27);
            label3.Text = "Điểm bán vé:";
            this.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            cboDiemBan.Name = "cboDiemBan";
            cboDiemBan.Location = new Point(135, 70);
            cboDiemBan.Size = new Size(240, 30);
            this.Controls.Add(cboDiemBan);
            label4.Name = "label4";
            label4.Location = new Point(405, 70);
            label4.Size = new Size(130, 27);
            label4.Text = "Người đăng ký:";
            this.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            txtTen.Name = "txtTen";
            txtTen.Location = new Point(535, 70);
            txtTen.Size = new Size(240, 30);
            this.Controls.Add(txtTen);
            label5.Name = "label5";
            label5.Location = new Point(830, 70);
            label5.Size = new Size(100, 27);
            label5.Text = "Điện thoại:";
            this.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            txtDT.Name = "txtDT";
            txtDT.Location = new Point(930, 70);
            txtDT.Size = new Size(215, 30);
            this.Controls.Add(txtDT);
            label6.Name = "label6";
            label6.Location = new Point(25, 120);
            label6.Size = new Size(110, 27);
            label6.Text = "Số người:";
            this.Controls.Add(label6);
            label6.TextAlign = ContentAlignment.MiddleLeft;
            numNguoi.Name = "numNguoi";
            numNguoi.Location = new Point(135, 120);
            numNguoi.Size = new Size(100, 30);
            this.Controls.Add(numNguoi);
            label7.Name = "label7";
            label7.Location = new Point(280, 120);
            label7.Size = new Size(120, 27);
            label7.Text = "Thành tiền:";
            this.Controls.Add(label7);
            label7.TextAlign = ContentAlignment.MiddleLeft;
            lblThanhTien.Name = "lblThanhTien";
            lblThanhTien.Location = new Point(400, 120);
            lblThanhTien.Size = new Size(220, 30);
            this.Controls.Add(lblThanhTien);
            btnDangKy.Name = "btnDangKy";
            btnDangKy.Location = new Point(980, 175);
            btnDangKy.Size = new Size(195, 40);
            btnDangKy.Text = "Đăng ký và thu tiền vé";
            this.Controls.Add(btnDangKy);
            btnDangKy.UseVisualStyleBackColor = true;
            btnDangKy.Click += btnDangKy_Click;
            dgv.Name = "dgv";
            dgv.Location = new Point(20, 235);
            dgv.Size = new Size(1160, 450);
            dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(dgv);
            dgv.BackgroundColor = Color.White;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.MultiSelect = false;
            dgv.RowTemplate.Height = 29;
            dgv.ColumnHeadersHeight = 30;
            cboChuyen.DropDownStyle = ComboBoxStyle.DropDownList;
            cboDiemBan.DropDownStyle = ComboBoxStyle.DropDownList;
            numNguoi.Minimum = 1m;
            numNguoi.Maximum = 11m;
            numNguoi.Value = 1m;
            numNguoi.ThousandsSeparator = true;
            lblThanhTien.Font = new Font("Segoe UI", 10F, FontStyle.Bold);
            lblThanhTien.Text = "-";
            lblThanhTien.ForeColor = Color.DarkRed;
            cboChuyen.SelectedIndexChanged += TinhTien;
            numNguoi.ValueChanged += TinhTien;
            Load += FrmDangKyLe_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmDangKyLe";
            Text = "Đăng ký khách lẻ";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private Label label1;
        private TextBox txtSo;
        private Label label2;
        private ComboBox cboChuyen;
        private Label label3;
        private ComboBox cboDiemBan;
        private Label label4;
        private TextBox txtTen;
        private Label label5;
        private TextBox txtDT;
        private Label label6;
        private NumericUpDown numNguoi;
        private Label label7;
        private Label lblThanhTien;
        private Button btnDangKy;
        private DataGridView dgv;
    }
}
