using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmPhanCongHDV
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            label1 = new Label();
            txtMaPC = new TextBox();
            label2 = new Label();
            cboHDV = new ComboBox();
            label3 = new Label();
            cboLoai = new ComboBox();
            label4 = new Label();
            cboDoiTuong = new ComboBox();
            label5 = new Label();
            numThuLao = new NumericUpDown();
            btnPhanCong = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            label1.Name = "label1";
            label1.Location = new Point(25, 20);
            label1.Size = new Size(145, 27);
            label1.Text = "Mã phân công:";
            this.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            txtMaPC.Name = "txtMaPC";
            txtMaPC.Location = new Point(170, 20);
            txtMaPC.Size = new Size(210, 30);
            this.Controls.Add(txtMaPC);
            label2.Name = "label2";
            label2.Location = new Point(375, 20);
            label2.Size = new Size(145, 27);
            label2.Text = "Hướng dẫn viên:";
            this.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            cboHDV.Name = "cboHDV";
            cboHDV.Location = new Point(520, 20);
            cboHDV.Size = new Size(420, 30);
            this.Controls.Add(cboHDV);
            label3.Name = "label3";
            label3.Location = new Point(25, 70);
            label3.Size = new Size(145, 27);
            label3.Text = "Loại: LE / DOAN:";
            this.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            cboLoai.Name = "cboLoai";
            cboLoai.Location = new Point(170, 70);
            cboLoai.Size = new Size(210, 30);
            this.Controls.Add(cboLoai);
            label4.Name = "label4";
            label4.Location = new Point(375, 70);
            label4.Size = new Size(145, 27);
            label4.Text = "Chuyến / đoàn:";
            this.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            cboDoiTuong.Name = "cboDoiTuong";
            cboDoiTuong.Location = new Point(520, 70);
            cboDoiTuong.Size = new Size(420, 30);
            this.Controls.Add(cboDoiTuong);
            label5.Name = "label5";
            label5.Location = new Point(25, 120);
            label5.Size = new Size(145, 27);
            label5.Text = "Thù lao tour:";
            this.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            numThuLao.Name = "numThuLao";
            numThuLao.Location = new Point(170, 120);
            numThuLao.Size = new Size(210, 30);
            this.Controls.Add(numThuLao);
            btnPhanCong.Name = "btnPhanCong";
            btnPhanCong.Location = new Point(980, 175);
            btnPhanCong.Size = new Size(195, 40);
            btnPhanCong.Text = "Phân công HDV";
            this.Controls.Add(btnPhanCong);
            btnPhanCong.UseVisualStyleBackColor = true;
            btnPhanCong.Click += btnPhanCong_Click;
            dgv.Name = "dgv";
            dgv.Location = new Point(20, 235);
            dgv.Size = new Size(1160, 450);
            dgv.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(dgv);
            dgv.BackgroundColor = Color.White;
            dgv.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgv.ReadOnly = true;
            dgv.AllowUserToAddRows = false;
            dgv.AllowUserToDeleteRows = false;
            dgv.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgv.MultiSelect = false;
            dgv.RowTemplate.Height = 29;
            dgv.ColumnHeadersHeight = 30;
            cboHDV.DropDownStyle = ComboBoxStyle.DropDownList;
            cboLoai.DropDownStyle = ComboBoxStyle.DropDownList;
            cboDoiTuong.DropDownStyle = ComboBoxStyle.DropDownList;
            numThuLao.Minimum = 0m;
            numThuLao.Maximum = 1000000000000m;
            numThuLao.Value = 0m;
            numThuLao.ThousandsSeparator = true;
            cboLoai.SelectedIndexChanged += cboLoai_SelectedIndexChanged;
            Load += FrmPhanCongHDV_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmPhanCongHDV";
            Text = "Phân công hướng dẫn viên";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private Label label1;
        private TextBox txtMaPC;
        private Label label2;
        private ComboBox cboHDV;
        private Label label3;
        private ComboBox cboLoai;
        private Label label4;
        private ComboBox cboDoiTuong;
        private Label label5;
        private NumericUpDown numThuLao;
        private Button btnPhanCong;
        private DataGridView dgv;
    }
}
