using System.Drawing;
using System.Windows.Forms;
namespace QuanLyCongTyDuLich.Forms
{
    partial class FrmTour
    {
        private System.ComponentModel.IContainer components = null;
        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent()
        {
            btnDong = new Button();
            tabs = new TabControl();
            label1 = new Label();
            cboTour = new ComboBox();
            tab0 = new TabPage();
            dgvTour = new DataGridView();
            label2 = new Label();
            txtMa = new TextBox();
            label3 = new Label();
            txtTen = new TextBox();
            label4 = new Label();
            numNgay = new NumericUpDown();
            label5 = new Label();
            numDem = new NumericUpDown();
            label6 = new Label();
            numGia = new NumericUpDown();
            label7 = new Label();
            txtMoTa = new TextBox();
            btnThemTour = new Button();
            tab1 = new TabPage();
            dgvDiemDung = new DataGridView();
            label8 = new Label();
            numThuTu = new NumericUpDown();
            label9 = new Label();
            txtDiemDung = new TextBox();
            chkDoiPT = new CheckBox();
            chkAn = new CheckBox();
            chkKS = new CheckBox();
            label10 = new Label();
            numSao = new NumericUpDown();
            label11 = new Label();
            txtGhiChuDD = new TextBox();
            btnThemDD = new Button();
            tab2 = new TabPage();
            dgvChang = new DataGridView();
            label12 = new Label();
            numChang = new NumericUpDown();
            label13 = new Label();
            cboPT = new ComboBox();
            label14 = new Label();
            txtGhiChuPT = new TextBox();
            btnThemChang = new Button();
            tab3 = new TabPage();
            dgvTQ = new DataGridView();
            label15 = new Label();
            cboDTQ = new ComboBox();
            label16 = new Label();
            numThuTuTQ = new NumericUpDown();
            btnThemTQ = new Button();
            SuspendLayout();
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            Font = new Font("Segoe UI", 10F);
            ClientSize = new Size(1200, 760);
            btnDong.Name = "btnDong";
            btnDong.Location = new Point(1050, 700);
            btnDong.Size = new Size(125, 40);
            btnDong.Text = "Đóng";
            btnDong.Anchor = AnchorStyles.Bottom | AnchorStyles.Right;
            this.Controls.Add(btnDong);
            btnDong.UseVisualStyleBackColor = true;
            btnDong.Click += btnDong_Click;
            tabs.Name = "tabs";
            tabs.Location = new Point(20, 65);
            tabs.Size = new Size(1160, 620);
            tabs.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            this.Controls.Add(tabs);
            label1.Name = "label1";
            label1.Location = new Point(25, 20);
            label1.Size = new Size(290, 27);
            label1.Text = "Tour đang chọn (cho các tab hành trình):";
            this.Controls.Add(label1);
            label1.TextAlign = ContentAlignment.MiddleLeft;
            cboTour.Name = "cboTour";
            cboTour.Location = new Point(315, 20);
            cboTour.Size = new Size(380, 30);
            this.Controls.Add(cboTour);
            tab0.Name = "tab0";
            tab0.Location = new Point(0, 0);
            tab0.Size = new Size(1150, 635);
            tab0.Text = "Tour";
            tabs.Controls.Add(tab0);
            tab0.UseVisualStyleBackColor = true;
            dgvTour.Name = "dgvTour";
            dgvTour.Location = new Point(15, 15);
            dgvTour.Size = new Size(1115, 385);
            dgvTour.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab0.Controls.Add(dgvTour);
            dgvTour.BackgroundColor = Color.White;
            dgvTour.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvTour.ReadOnly = true;
            dgvTour.AllowUserToAddRows = false;
            dgvTour.AllowUserToDeleteRows = false;
            dgvTour.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvTour.MultiSelect = false;
            dgvTour.RowTemplate.Height = 29;
            dgvTour.ColumnHeadersHeight = 30;
            label2.Name = "label2";
            label2.Location = new Point(20, 420);
            label2.Size = new Size(100, 27);
            label2.Text = "Mã tour:";
            label2.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label2);
            label2.TextAlign = ContentAlignment.MiddleLeft;
            txtMa.Name = "txtMa";
            txtMa.Location = new Point(120, 420);
            txtMa.Size = new Size(150, 30);
            txtMa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtMa);
            label3.Name = "label3";
            label3.Location = new Point(310, 420);
            label3.Size = new Size(100, 27);
            label3.Text = "Tên tour:";
            label3.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label3);
            label3.TextAlign = ContentAlignment.MiddleLeft;
            txtTen.Name = "txtTen";
            txtTen.Location = new Point(410, 420);
            txtTen.Size = new Size(460, 30);
            txtTen.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtTen);
            label4.Name = "label4";
            label4.Location = new Point(20, 468);
            label4.Size = new Size(100, 27);
            label4.Text = "Số ngày:";
            label4.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label4);
            label4.TextAlign = ContentAlignment.MiddleLeft;
            numNgay.Name = "numNgay";
            numNgay.Location = new Point(120, 468);
            numNgay.Size = new Size(100, 30);
            numNgay.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(numNgay);
            label5.Name = "label5";
            label5.Location = new Point(310, 468);
            label5.Size = new Size(100, 27);
            label5.Text = "Số đêm:";
            label5.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label5);
            label5.TextAlign = ContentAlignment.MiddleLeft;
            numDem.Name = "numDem";
            numDem.Location = new Point(410, 468);
            numDem.Size = new Size(100, 30);
            numDem.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(numDem);
            label6.Name = "label6";
            label6.Location = new Point(570, 468);
            label6.Size = new Size(150, 27);
            label6.Text = "Đơn giá / khách:";
            label6.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label6);
            label6.TextAlign = ContentAlignment.MiddleLeft;
            numGia.Name = "numGia";
            numGia.Location = new Point(720, 468);
            numGia.Size = new Size(210, 30);
            numGia.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(numGia);
            label7.Name = "label7";
            label7.Location = new Point(20, 516);
            label7.Size = new Size(100, 27);
            label7.Text = "Mô tả:";
            label7.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(label7);
            label7.TextAlign = ContentAlignment.MiddleLeft;
            txtMoTa.Name = "txtMoTa";
            txtMoTa.Location = new Point(120, 516);
            txtMoTa.Size = new Size(770, 30);
            txtMoTa.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(txtMoTa);
            btnThemTour.Name = "btnThemTour";
            btnThemTour.Location = new Point(920, 516);
            btnThemTour.Size = new Size(180, 40);
            btnThemTour.Text = "Thêm tour";
            btnThemTour.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab0.Controls.Add(btnThemTour);
            btnThemTour.UseVisualStyleBackColor = true;
            btnThemTour.Click += btnThemTour_Click;
            tab1.Name = "tab1";
            tab1.Location = new Point(0, 0);
            tab1.Size = new Size(1150, 635);
            tab1.Text = "Điểm dừng";
            tabs.Controls.Add(tab1);
            tab1.UseVisualStyleBackColor = true;
            dgvDiemDung.Name = "dgvDiemDung";
            dgvDiemDung.Location = new Point(15, 15);
            dgvDiemDung.Size = new Size(1115, 385);
            dgvDiemDung.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab1.Controls.Add(dgvDiemDung);
            dgvDiemDung.BackgroundColor = Color.White;
            dgvDiemDung.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvDiemDung.ReadOnly = true;
            dgvDiemDung.AllowUserToAddRows = false;
            dgvDiemDung.AllowUserToDeleteRows = false;
            dgvDiemDung.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvDiemDung.MultiSelect = false;
            dgvDiemDung.RowTemplate.Height = 29;
            dgvDiemDung.ColumnHeadersHeight = 30;
            label8.Name = "label8";
            label8.Location = new Point(20, 420);
            label8.Size = new Size(100, 27);
            label8.Text = "Thứ tự:";
            label8.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label8);
            label8.TextAlign = ContentAlignment.MiddleLeft;
            numThuTu.Name = "numThuTu";
            numThuTu.Location = new Point(120, 420);
            numThuTu.Size = new Size(100, 30);
            numThuTu.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(numThuTu);
            label9.Name = "label9";
            label9.Location = new Point(280, 420);
            label9.Size = new Size(145, 27);
            label9.Text = "Tên điểm dừng:";
            label9.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label9);
            label9.TextAlign = ContentAlignment.MiddleLeft;
            txtDiemDung.Name = "txtDiemDung";
            txtDiemDung.Location = new Point(425, 420);
            txtDiemDung.Size = new Size(380, 30);
            txtDiemDung.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtDiemDung);
            chkDoiPT.Name = "chkDoiPT";
            chkDoiPT.Location = new Point(20, 468);
            chkDoiPT.Size = new Size(200, 30);
            chkDoiPT.Text = "Đổi phương tiện";
            chkDoiPT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(chkDoiPT);
            chkAn.Name = "chkAn";
            chkAn.Location = new Point(260, 468);
            chkAn.Size = new Size(170, 30);
            chkAn.Text = "Có nơi ăn";
            chkAn.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(chkAn);
            chkKS.Name = "chkKS";
            chkKS.Location = new Point(450, 468);
            chkKS.Size = new Size(180, 30);
            chkKS.Text = "Có khách sạn";
            chkKS.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(chkKS);
            label10.Name = "label10";
            label10.Location = new Point(650, 468);
            label10.Size = new Size(100, 27);
            label10.Text = "Hạng sao:";
            label10.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label10);
            label10.TextAlign = ContentAlignment.MiddleLeft;
            numSao.Name = "numSao";
            numSao.Location = new Point(750, 468);
            numSao.Size = new Size(100, 30);
            numSao.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(numSao);
            label11.Name = "label11";
            label11.Location = new Point(20, 516);
            label11.Size = new Size(100, 27);
            label11.Text = "Ghi chú:";
            label11.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(label11);
            label11.TextAlign = ContentAlignment.MiddleLeft;
            txtGhiChuDD.Name = "txtGhiChuDD";
            txtGhiChuDD.Location = new Point(120, 516);
            txtGhiChuDD.Size = new Size(770, 30);
            txtGhiChuDD.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(txtGhiChuDD);
            btnThemDD.Name = "btnThemDD";
            btnThemDD.Location = new Point(920, 564);
            btnThemDD.Size = new Size(180, 40);
            btnThemDD.Text = "Thêm điểm dừng";
            btnThemDD.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab1.Controls.Add(btnThemDD);
            btnThemDD.UseVisualStyleBackColor = true;
            btnThemDD.Click += btnThemDD_Click;
            tab2.Name = "tab2";
            tab2.Location = new Point(0, 0);
            tab2.Size = new Size(1150, 635);
            tab2.Text = "Chặng phương tiện";
            tabs.Controls.Add(tab2);
            tab2.UseVisualStyleBackColor = true;
            dgvChang.Name = "dgvChang";
            dgvChang.Location = new Point(15, 15);
            dgvChang.Size = new Size(1115, 385);
            dgvChang.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab2.Controls.Add(dgvChang);
            dgvChang.BackgroundColor = Color.White;
            dgvChang.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvChang.ReadOnly = true;
            dgvChang.AllowUserToAddRows = false;
            dgvChang.AllowUserToDeleteRows = false;
            dgvChang.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvChang.MultiSelect = false;
            dgvChang.RowTemplate.Height = 29;
            dgvChang.ColumnHeadersHeight = 30;
            label12.Name = "label12";
            label12.Location = new Point(20, 420);
            label12.Size = new Size(100, 27);
            label12.Text = "Thứ tự chặng:";
            label12.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label12);
            label12.TextAlign = ContentAlignment.MiddleLeft;
            numChang.Name = "numChang";
            numChang.Location = new Point(120, 420);
            numChang.Size = new Size(100, 30);
            numChang.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(numChang);
            label13.Name = "label13";
            label13.Location = new Point(300, 420);
            label13.Size = new Size(120, 27);
            label13.Text = "Phương tiện:";
            label13.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label13);
            label13.TextAlign = ContentAlignment.MiddleLeft;
            cboPT.Name = "cboPT";
            cboPT.Location = new Point(420, 420);
            cboPT.Size = new Size(270, 30);
            cboPT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(cboPT);
            label14.Name = "label14";
            label14.Location = new Point(20, 468);
            label14.Size = new Size(100, 27);
            label14.Text = "Ghi chú:";
            label14.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(label14);
            label14.TextAlign = ContentAlignment.MiddleLeft;
            txtGhiChuPT.Name = "txtGhiChuPT";
            txtGhiChuPT.Location = new Point(120, 468);
            txtGhiChuPT.Size = new Size(770, 30);
            txtGhiChuPT.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(txtGhiChuPT);
            btnThemChang.Name = "btnThemChang";
            btnThemChang.Location = new Point(920, 468);
            btnThemChang.Size = new Size(180, 40);
            btnThemChang.Text = "Gán phương tiện";
            btnThemChang.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab2.Controls.Add(btnThemChang);
            btnThemChang.UseVisualStyleBackColor = true;
            btnThemChang.Click += btnThemChang_Click;
            tab3.Name = "tab3";
            tab3.Location = new Point(0, 0);
            tab3.Size = new Size(1150, 635);
            tab3.Text = "Điểm tham quan";
            tabs.Controls.Add(tab3);
            tab3.UseVisualStyleBackColor = true;
            dgvTQ.Name = "dgvTQ";
            dgvTQ.Location = new Point(15, 15);
            dgvTQ.Size = new Size(1115, 385);
            dgvTQ.Anchor = AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right;
            tab3.Controls.Add(dgvTQ);
            dgvTQ.BackgroundColor = Color.White;
            dgvTQ.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            dgvTQ.ReadOnly = true;
            dgvTQ.AllowUserToAddRows = false;
            dgvTQ.AllowUserToDeleteRows = false;
            dgvTQ.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
            dgvTQ.MultiSelect = false;
            dgvTQ.RowTemplate.Height = 29;
            dgvTQ.ColumnHeadersHeight = 30;
            label15.Name = "label15";
            label15.Location = new Point(20, 420);
            label15.Size = new Size(155, 27);
            label15.Text = "Điểm tham quan:";
            label15.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label15);
            label15.TextAlign = ContentAlignment.MiddleLeft;
            cboDTQ.Name = "cboDTQ";
            cboDTQ.Location = new Point(175, 420);
            cboDTQ.Size = new Size(370, 30);
            cboDTQ.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(cboDTQ);
            label16.Name = "label16";
            label16.Location = new Point(620, 420);
            label16.Size = new Size(100, 27);
            label16.Text = "Thứ tự:";
            label16.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(label16);
            label16.TextAlign = ContentAlignment.MiddleLeft;
            numThuTuTQ.Name = "numThuTuTQ";
            numThuTuTQ.Location = new Point(720, 420);
            numThuTuTQ.Size = new Size(100, 30);
            numThuTuTQ.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(numThuTuTQ);
            btnThemTQ.Name = "btnThemTQ";
            btnThemTQ.Location = new Point(920, 468);
            btnThemTQ.Size = new Size(180, 40);
            btnThemTQ.Text = "Gán điểm tham quan";
            btnThemTQ.Anchor = AnchorStyles.Bottom | AnchorStyles.Left;
            tab3.Controls.Add(btnThemTQ);
            btnThemTQ.UseVisualStyleBackColor = true;
            btnThemTQ.Click += btnThemTQ_Click;
            cboTour.DropDownStyle = ComboBoxStyle.DropDownList;
            numNgay.Minimum = 1m;
            numNgay.Maximum = 365m;
            numNgay.Value = 1m;
            numNgay.ThousandsSeparator = true;
            numDem.Minimum = 0m;
            numDem.Maximum = 365m;
            numDem.Value = 0m;
            numDem.ThousandsSeparator = true;
            numGia.Minimum = 0m;
            numGia.Maximum = 1000000000000m;
            numGia.Value = 0m;
            numGia.ThousandsSeparator = true;
            numThuTu.Minimum = 1m;
            numThuTu.Maximum = 365m;
            numThuTu.Value = 1m;
            numThuTu.ThousandsSeparator = true;
            numSao.Minimum = 2m;
            numSao.Maximum = 5m;
            numSao.Value = 2m;
            numSao.ThousandsSeparator = true;
            numChang.Minimum = 1m;
            numChang.Maximum = 365m;
            numChang.Value = 1m;
            numChang.ThousandsSeparator = true;
            cboPT.DropDownStyle = ComboBoxStyle.DropDownList;
            cboDTQ.DropDownStyle = ComboBoxStyle.DropDownList;
            numThuTuTQ.Minimum = 1m;
            numThuTuTQ.Maximum = 365m;
            numThuTuTQ.Value = 1m;
            numThuTuTQ.ThousandsSeparator = true;
            numSao.Enabled = false;
            cboTour.SelectedIndexChanged += cboTour_SelectedIndexChanged;
            chkKS.CheckedChanged += chkKS_CheckedChanged;
            Load += FrmTour_Load;
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            ClientSize = new Size(1200, 760);
            MinimumSize = new Size(1216, 799);
            Font = new Font("Segoe UI", 10F);
            Name = "FrmTour";
            Text = "Tour và hành trình";
            StartPosition = FormStartPosition.CenterScreen;
            ResumeLayout(false);
            PerformLayout();
        }
        private Button btnDong;
        private TabControl tabs;
        private Label label1;
        private ComboBox cboTour;
        private TabPage tab0;
        private DataGridView dgvTour;
        private Label label2;
        private TextBox txtMa;
        private Label label3;
        private TextBox txtTen;
        private Label label4;
        private NumericUpDown numNgay;
        private Label label5;
        private NumericUpDown numDem;
        private Label label6;
        private NumericUpDown numGia;
        private Label label7;
        private TextBox txtMoTa;
        private Button btnThemTour;
        private TabPage tab1;
        private DataGridView dgvDiemDung;
        private Label label8;
        private NumericUpDown numThuTu;
        private Label label9;
        private TextBox txtDiemDung;
        private CheckBox chkDoiPT;
        private CheckBox chkAn;
        private CheckBox chkKS;
        private Label label10;
        private NumericUpDown numSao;
        private Label label11;
        private TextBox txtGhiChuDD;
        private Button btnThemDD;
        private TabPage tab2;
        private DataGridView dgvChang;
        private Label label12;
        private NumericUpDown numChang;
        private Label label13;
        private ComboBox cboPT;
        private Label label14;
        private TextBox txtGhiChuPT;
        private Button btnThemChang;
        private TabPage tab3;
        private DataGridView dgvTQ;
        private Label label15;
        private ComboBox cboDTQ;
        private Label label16;
        private NumericUpDown numThuTuTQ;
        private Button btnThemTQ;
    }
}
